get_pizza:
  path: /
  defaults: { _controller: PizzaCatalogBundle:Pizza:get, _format: html }

get_pizza_by_id:
    path:  /get/{id}
    defaults: { _controller: "PizzaCatalogBundle:Pizza:update", _format: html }
    methods:  [GET]
    requirements:
        pizza_id: \d+

post_pizza:
    path:  /update/{id}
    defaults: { _controller: "PizzaCatalogBundle:Pizza:update", _format: html }
    methods:  [POST]
    requirements:
        id: \d+
